export const combinedCropAndFreshProducts = [
  {
    id: "fruit-01",
    productName: "Organic Gala Apples",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/redApple.jpg`,
    images: [
      "https://res.cloudinary.com/dauwvxrrf/image/upload/v1762785825/redApple_vq2bdr.jpg",
    ],
    description:
      "Freshly picked organic Gala apples, rich in flavor and nutrients. Ideal for snacking or baking.",
    specs: { origin: "Local Farms", size: "Medium", organic: true },
    rating: 4,
    reviews: [
      {
        name: "Ali",
        comment: "Crisp and delicious!",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/10.jpg",
        reviewDate: "2025-06-01",
        likesCount: 15,
      },
      {
        name: "Sara",
        comment: "Perfect for my fruit salad.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/20.jpg",
        reviewDate: "2025-06-02",
        likesCount: 19,
      },
    ],
    stock: 34,
    price: "60 EGP/kg",
    discountPrice: "52 EGP/kg",
    category: "Fruits",
    tags: ["Fruit", "Organic", "Fresh", "Popular"],
  },
  {
    id: "fruit-02",
    productName: "Bananas",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/bananas.jpg`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/bananas.jpg`,
    ],
    description:
      "Naturally sweet and full of potassium, our bananas are ideal for a healthy snack or smoothie.",
    specs: { origin: "Upper Egypt", ripeness: "Medium", size: "Large" },
    rating: 3,
    reviews: [
      {
        name: "Khaled",
        comment: "Nice and soft.",
        rating: 3,
        image: "https://randomuser.me/api/portraits/men/33.jpg",
        reviewDate: "2025-06-01",
        likesCount: 7,
      },
      {
        name: "Noura",
        comment: "Good for smoothies.",
        rating: 3,
        image: "https://randomuser.me/api/portraits/women/27.jpg",
        reviewDate: "2025-06-04",
        likesCount: 12,
      },
    ],
    stock: 40,
    price: "32 EGP/kg",
    discountPrice: "28 EGP/kg",
    category: "Fruits",
    tags: ["Fruit", "Tropical", "Fresh"],
  },
  {
    id: "fruit-03",
    productName: "Grapes",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/grapes.jpg`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/grapes.jpg`,
    ],
    description:
      "Sweet and juicy grapes perfect for snacking or making juice. Grown without synthetic pesticides.",
    specs: { color: "Red", seedless: true, weight: "1kg" },
    rating: 5,
    reviews: [
      {
        name: "Samir",
        comment: "Very sweet and fresh.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/22.jpg",
        reviewDate: "2025-06-03",
        likesCount: 17,
      },
      {
        name: "Fatma",
        comment: "Kids love them!",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/48.jpg",
        reviewDate: "2025-06-06",
        likesCount: 22,
      },
    ],
    stock: 25,
    price: "65 EGP/kg",
    discountPrice: "60 EGP/kg",
    category: "Fruits",
    tags: ["Fruit", "Sweet", "Fresh"],
  },
  {
    id: "fruit-04",
    productName: "Green Apples",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/greenApple.jpg`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/greenApple.jpg`,
    ],
    description:
      "Tangy and crisp green apples, perfect for juicing or baking pies.",
    specs: { taste: "Tart", skin: "Shiny", size: "Medium" },
    rating: 2,
    reviews: [
      {
        name: "Mona",
        comment: "A bit too sour for me.",
        rating: 2,
        image: "https://randomuser.me/api/portraits/women/34.jpg",
        reviewDate: "2025-06-05",
        likesCount: 5,
      },
      {
        name: "Ahmed",
        comment: "Exactly what I wanted.",
        rating: 3,
        image: "https://randomuser.me/api/portraits/men/13.jpg",
        reviewDate: "2025-06-07",
        likesCount: 9,
      },
    ],
    stock: 20,
    price: "50 EGP/kg",
    discountPrice: "45 EGP/kg",
    category: "Fruits",
    tags: ["Fruit", "Tart", "Fresh"],
  },
  {
    id: "fruit-05",
    productName: "Pears",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/pears.jpg`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/pears.jpg`,
    ],
    description:
      "Juicy and mellow pears perfect for snacking and desserts. Rich in fiber and vitamin C.",
    specs: { origin: "Delta", type: "Bartlett", size: "Large" },
    rating: 4,
    reviews: [
      {
        name: "Omar",
        comment: "Fresh and tasty pears.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/44.jpg",
        reviewDate: "2025-06-09",
        likesCount: 14,
      },
      {
        name: "Laila",
        comment: "Great for baking pies.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/56.jpg",
        reviewDate: "2025-06-10",
        likesCount: 18,
      },
    ],
    stock: 30,
    price: "75 EGP/kg",
    discountPrice: "68 EGP/kg",
    category: "Fruits",
    tags: ["Fruit", "Juicy", "Fresh"],
  },
  {
    id: "fruit-06",
    productName: "Fig",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/fig.jpg`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/fig.jpg`,
    ],
    description:
      "Sweet seasonal figs loaded with antioxidants and dietary fiber.",
    specs: { variety: "Black Mission", texture: "Soft", organic: false },
    rating: 3,
    reviews: [
      {
        name: "Nada",
        comment: "Very soft and tasty.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/38.jpg",
        reviewDate: "2025-06-11",
        likesCount: 13,
      },
      {
        name: "Hussein",
        comment: "A bit overripe.",
        rating: 2,
        image: "https://randomuser.me/api/portraits/men/39.jpg",
        reviewDate: "2025-06-12",
        likesCount: 9,
      },
    ],
    stock: 16,
    price: "28 EGP/kg",
    discountPrice: "24 EGP/kg",
    category: "Fruits",
    tags: ["Fruit", "Seasonal", "Sweet"],
  },
  {
    id: "fruit-07",
    productName: "Strawberry",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/strawberry.jpg`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/strawberry.jpg`,
    ],
    description:
      "*Note: Product image is strawberry. Verify name.* Likely to be fresh strawberries – juicy and sweet.",
    specs: { origin: "Coastal", season: "Spring", type: "Fresh berries" },
    rating: 3,
    reviews: [
      {
        name: "Ali",
        comment: "Fresh but mislabeled?",
        rating: 3,
        image: "https://randomuser.me/api/portraits/men/20.jpg",
        reviewDate: "2025-06-14",
        likesCount: 6,
      },
    ],
    stock: 22,
    price: "35 EGP/kg",
    discountPrice: "30 EGP/kg",
    category: "Fruits",
    tags: ["Fruit", "Seasonal", "Fresh"],
  },
  {
    id: "vege-01",
    productName: "Tomato",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/tomato1.jpg`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/tomato1.jpg`,
    ],
    description:
      "Juicy and ripe tomatoes perfect for salads, sauces, and everyday cooking.",
    specs: { origin: "Local farms", type: "Roma", shelfLife: "7 days" },
    rating: 4,
    reviews: [
      {
        name: "Alaa",
        comment: "Very fresh and tasty.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/33.jpg",
        reviewDate: "2025-06-20",
        likesCount: 16,
      },
      {
        name: "Sara",
        comment: "Nice flavor and good size.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/36.jpg",
        reviewDate: "2025-06-21",
        likesCount: 12,
      },
    ],
    stock: 24,
    price: "42 EGP/kg",
    discountPrice: "36 EGP/kg",
    category: "Vegetables",
    tags: ["Vegetable", "Essential", "Fresh"],
  },
  {
    id: "vege-02",
    productName: "onion",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/onion1.jpg`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/onion1.jpg`,
    ],
    description:
      "Aromatic and versatile onions great for cooking and garnishing.",
    specs: {
      origin: "Delta region",
      type: "Yellow onion",
      shelfLife: "30 days",
    },
    rating: 4,
    reviews: [
      {
        name: "Mahmoud",
        comment: "Good quality, arrived fresh.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/40.jpg",
        reviewDate: "2025-06-20",
        likesCount: 10,
      },
      {
        name: "Nora",
        comment: "Perfect for cooking.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/41.jpg",
        reviewDate: "2025-06-22",
        likesCount: 13,
      },
    ],
    stock: 35,
    price: "35 EGP/kg",
    discountPrice: "30 EGP/kg",
    category: "Vegetables",
    tags: ["Vegetable", "Aromatic", "Essential"],
  },
  {
    id: "vege-03",
    productName: "Potato",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/potato1.jpg`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/potato1.jpg`,
    ],
    description: "Staple food with a rich source of carbohydrates and fiber.",
    specs: { origin: "Upper Egypt", type: "Spunta", shelfLife: "25 days" },
    rating: 3,
    reviews: [
      {
        name: "Ali",
        comment: "Fair size and taste.",
        rating: 3,
        image: "https://randomuser.me/api/portraits/men/50.jpg",
        reviewDate: "2025-06-19",
        likesCount: 9,
      },
      {
        name: "Mona",
        comment: "Good for frying and boiling.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/49.jpg",
        reviewDate: "2025-06-20",
        likesCount: 14,
      },
    ],
    stock: 40,
    price: "20 EGP/kg",
    discountPrice: "17 EGP/kg",
    category: "Vegetables",
    tags: ["Vegetable", "Starchy", "Essential"],
  },
  {
    id: "vege-04",
    productName: "Carrot",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/carrot1.jpg`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/carrot1.jpg`,
    ],
    description: "Crunchy, sweet carrots full of vitamins and antioxidants.",
    specs: { origin: "Ismailia", type: "Nantes", shelfLife: "14 days" },
    rating: 5,
    reviews: [
      {
        name: "Youssef",
        comment: "Very sweet and crisp.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/60.jpg",
        reviewDate: "2025-06-23",
        likesCount: 18,
      },
      {
        name: "Lina",
        comment: "Kids love them.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/59.jpg",
        reviewDate: "2025-06-24",
        likesCount: 22,
      },
    ],
    stock: 20,
    price: "55 EGP/kg",
    discountPrice: "48 EGP/kg",
    category: "Vegetables",
    tags: ["Vegetable", "Root", "Sweet"],
  },
  {
    id: "vege-05",
    productName: "Cucumbers",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/cucumbers.jpg`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/cucumbers.jpg`,
    ],
    description: "Fresh and crisp cucumbers ideal for salads and hydration.",
    specs: { origin: "Local Farms", size: "Medium", freshness: "High" },
    rating: 4,
    reviews: [
      {
        name: "Mona",
        comment: "Very fresh and crunchy!",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/12.jpg",
        reviewDate: "2025-06-10",
        likesCount: 10,
      },
      {
        name: "Ali",
        comment: "Best cucumbers I've had this season.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/35.jpg",
        reviewDate: "2025-06-11",
        likesCount: 14,
      },
      {
        name: "Yara",
        comment: "Cool and refreshing, great with yogurt.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/52.jpg",
        reviewDate: "2025-06-12",
        likesCount: 13,
      },
    ],
    stock: 22,
    price: "30 EGP/kg",
    discountPrice: "27 EGP/kg",
    category: "Vegetables",
    tags: ["Vegetable", "Cool", "Hydrating"],
  },
  {
    id: "vege-06",
    productName: "Cauliflower",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/cauliflower.jpg`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/cauliflower.jpg`,
    ],
    description:
      "Nutritious and versatile white cauliflower, great for roasting or steaming.",
    specs: { size: "Large Head", freshness: "High", shelfLife: "4 days" },
    rating: 4,
    reviews: [
      {
        name: "Hassan",
        comment: "Big head and really fresh.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/44.jpg",
        reviewDate: "2025-06-13",
        likesCount: 11,
      },
      {
        name: "Salma",
        comment: "Perfect for my veggie dishes.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/41.jpg",
        reviewDate: "2025-06-14",
        likesCount: 15,
      },
      {
        name: "Omar",
        comment: "Clean and tastes great!",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/25.jpg",
        reviewDate: "2025-06-15",
        likesCount: 12,
      },
    ],
    stock: 16,
    price: "35 EGP/kg",
    discountPrice: "30 EGP/kg",
    category: "Vegetables",
    tags: ["Vegetable", "Cruciferous", "White"],
  },
  {
    id: "vege-07",
    productName: "Corn",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/corn.jpg`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/corn.jpg`,
    ],
    description:
      "Golden yellow corn, sweet and juicy – perfect for grilling or boiling.",
    specs: { kernelType: "Sweet", packaging: "Loose", origin: "Nile Valley" },
    rating: 4,
    reviews: [
      {
        name: "Noor",
        comment: "Juicy and super sweet.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/60.jpg",
        reviewDate: "2025-06-16",
        likesCount: 13,
      },
      {
        name: "Ibrahim",
        comment: "Great flavor when grilled.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/37.jpg",
        reviewDate: "2025-06-17",
        likesCount: 15,
      },
      {
        name: "Rania",
        comment: "Loved it! Will buy again.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/23.jpg",
        reviewDate: "2025-06-18",
        likesCount: 17,
      },
    ],
    stock: 18,
    price: "30 EGP/kg",
    discountPrice: "27 EGP/kg",
    category: "Vegetables",
    tags: ["Vegetable", "Grain", "Sweet"],
  },
  {
    id: "vege-08",
    productName: "Chili Peppers",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/chiliPeppers.jpg`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/chiliPeppers.jpg`,
    ],
    description: "Spicy red chili peppers for cooking and pickling.",
    specs: { spiceLevel: "High", color: "Red", shelfLife: "5 days" },
    rating: 4,
    reviews: [
      {
        name: "Ahmed",
        comment: "Hot and fresh, just like I love it!",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/31.jpg",
        reviewDate: "2025-06-19",
        likesCount: 14,
      },
      {
        name: "Dina",
        comment: "Adds great kick to food.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/34.jpg",
        reviewDate: "2025-06-20",
        likesCount: 11,
      },
      {
        name: "Mahmoud",
        comment: "Strong flavor, very spicy!",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/29.jpg",
        reviewDate: "2025-06-21",
        likesCount: 12,
      },
    ],
    stock: 21,
    price: "32 EGP/kg",
    discountPrice: "28 EGP/kg",
    category: "Vegetables",
    tags: ["Vegetable", "Spicy", "Hot"],
  },
  {
    id: "vege-09",
    productName: "Lemon",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/lemon.jpg`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/lemon.jpg`,
    ],
    description:
      "Fresh yellow lemons rich in vitamin C, perfect for seasoning and beverages.",
    specs: { size: "Medium", acidity: "High", freshness: "Excellent" },
    rating: 4,
    reviews: [
      {
        name: "Nada",
        comment: "Perfect for lemonade and detox drinks.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/15.jpg",
        reviewDate: "2025-06-20",
        likesCount: 12,
      },
      {
        name: "Mostafa",
        comment: "Very juicy and fresh.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/21.jpg",
        reviewDate: "2025-06-21",
        likesCount: 10,
      },
      {
        name: "Rania",
        comment: "Love using it in cooking and tea!",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/38.jpg",
        reviewDate: "2025-06-22",
        likesCount: 15,
      },
    ],
    stock: 19,
    price: "30 EGP/kg",
    discountPrice: "26 EGP/kg",
    category: "Fruit",
    tags: ["Fruit", "Citrus", "Sour"],
  },
  {
    id: "vege-10",
    productName: "Peas",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/peas.jpg`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/CropsAndFreshProduces/peas.jpg`,
    ],
    description: "Sweet green peas, perfect for soups, stews, and rice dishes.",
    specs: { podType: "Green", taste: "Sweet", freshness: "High" },
    rating: 4,
    reviews: [
      {
        name: "Khaled",
        comment: "Sweet and clean, great with rice.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/32.jpg",
        reviewDate: "2025-06-21",
        likesCount: 13,
      },
      {
        name: "Salma",
        comment: "Perfect for pea soup.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/50.jpg",
        reviewDate: "2025-06-22",
        likesCount: 12,
      },
      {
        name: "Hassan",
        comment: "Really fresh and tasty.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/26.jpg",
        reviewDate: "2025-06-23",
        likesCount: 14,
      },
    ],
    stock: 20,
    price: "34 EGP/kg",
    discountPrice: "30 EGP/kg",
    category: "Vegetable",
    tags: ["Vegetable", "Legume", "Green"],
  },
];
