export const combinedSeedAndSaplingProducts = [
  {
    id: "seed-01",
    productName: "Burpee Sweet Pepper Seeds",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/SeedsAndSaplings/burpeeSweetPepperSeeds.webp`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/SeedsAndSaplings/burpeeSweetPepperSeeds.webp`,
    ],
    description:
      "High-quality sweet pepper seeds from Burpee, perfect for home gardening. Produces vibrant, sweet peppers ideal for salads and cooking. Easy to grow with high germination rates.",
    specs: {
      type: "Sweet Pepper",
      brand: "Burpee",
      germination: "7-14 days",
      season: "Spring/Summer",
      packSize: "50 seeds",
    },
    rating: 4.6,
    reviews: [
      {
        name: "Ahmed",
        comment: "Great germination rate! All seeds sprouted perfectly.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/32.jpg",
        reviewDate: "2025-06-15",
        likesCount: 12,
      },
      {
        name: "Fatima",
        comment: "Peppers grew exactly as described. Very sweet!",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/45.jpg",
        reviewDate: "2025-06-20",
        likesCount: 8,
      },
    ],
    stock: 45,
    price: "18 EGP/pack",
    discountPrice: "15 EGP/pack",
    category: "Seeds",
    tags: ["Seeds", "Vegetable", "Pepper", "Cultivation"],
  },
  {
    id: "seed-02",
    productName: "Burpee Carrot Seeds",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/SeedsAndSaplings/burpeeCarrotSeeds.webp`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/SeedsAndSaplings/burpeeCarrotSeeds.webp`,
    ],
    description:
      "Premium carrot seeds that produce crisp, sweet carrots perfect for fresh eating or cooking. These Nantes-type carrots grow straight and uniform with excellent flavor.",
    specs: {
      type: "Carrot",
      brand: "Burpee",
      germination: "10-21 days",
      season: "Cool Weather",
      variety: "Nantes",
      packSize: "200 seeds",
    },
    rating: 4.5,
    reviews: [
      {
        name: "Mohamed",
        comment: "Carrots grew straight and sweet. Very satisfied!",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/28.jpg",
        reviewDate: "2025-06-18",
        likesCount: 10,
      },
      {
        name: "Layla",
        comment: "Good yield from one packet. Will buy again.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/33.jpg",
        reviewDate: "2025-06-22",
        likesCount: 7,
      },
    ],
    stock: 38,
    price: "12 EGP/pack",
    discountPrice: "10 EGP/pack",
    category: "Seeds",
    tags: ["Seeds", "Vegetable", "Carrot", "Root"],
  },
  {
    id: "seed-03",
    productName: "Burpee Pea Seeds",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/SeedsAndSaplings/burpeePeaSeeds.webp`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/SeedsAndSaplings/burpeePeaSeeds.webp`,
    ],
    description:
      "Delicious pea seeds that produce abundant yields of sweet, tender peas. Perfect for spring planting, these peas are great for fresh eating, freezing, or canning.",
    specs: {
      type: "Garden Pea",
      brand: "Burpee",
      germination: "7-14 days",
      season: "Early Spring",
      growth: "Vining",
      packSize: "100 seeds",
    },
    rating: 4.4,
    reviews: [
      {
        name: "Youssef",
        comment: "Pods were full and peas very sweet. Excellent!",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/41.jpg",
        reviewDate: "2025-06-14",
        likesCount: 9,
      },
      {
        name: "Nadia",
        comment: "Easy to grow and very productive plants.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/29.jpg",
        reviewDate: "2025-06-19",
        likesCount: 11,
      },
    ],
    stock: 52,
    price: "20 EGP/pack",
    discountPrice: "17 EGP/pack",
    category: "Seeds",
    tags: ["Seeds", "Vegetable", "Pea", "Legume"],
  },
  {
    id: "seed-04",
    productName: "Burpee Watermelon Seeds",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/SeedsAndSaplings/burpeeWatermelonSeeds.webp`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/SeedsAndSaplings/burpeeWatermelonSeeds.webp`,
    ],
    description:
      "Sweet, juicy watermelon seeds that produce large, refreshing melons perfect for summer. These seeds grow into vigorous vines that yield 8-10 kg fruits with deep red, sweet flesh.",
    specs: {
      type: "Watermelon",
      brand: "Burpee",
      germination: "5-10 days",
      season: "Summer",
      fruitSize: "8-10 kg",
      daysToMaturity: "85-95 days",
      packSize: "25 seeds",
    },
    rating: 4.8,
    reviews: [
      {
        name: "Karim",
        comment: "Best watermelon I've ever grown! Super sweet and juicy.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/35.jpg",
        reviewDate: "2025-06-25",
        likesCount: 15,
      },
      {
        name: "Sana",
        comment: "Huge watermelons with perfect texture. Family loved them!",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/42.jpg",
        reviewDate: "2025-06-28",
        likesCount: 13,
      },
    ],
    stock: 28,
    price: "22 EGP/pack",
    discountPrice: "19 EGP/pack",
    category: "Seeds",
    tags: ["Seeds", "Fruit", "Watermelon", "Summer"],
  },
  {
    id: "seed-05",
    productName: "Ferry Morse Tomato Seeds",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/SeedsAndSaplings/ferryTomatoSeeds.webp`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/SeedsAndSaplings/ferryTomatoSeeds.webp`,
    ],
    description:
      "Reliable tomato seeds from Ferry Morse that produce robust plants with abundant, flavorful tomatoes. Perfect for slicing, salads, and cooking with consistent results.",
    specs: {
      type: "Tomato",
      brand: "Ferry Morse",
      germination: "6-12 days",
      season: "Spring/Summer",
      fruitType: "Slicing",
      daysToMaturity: "70-80 days",
      packSize: "50 seeds",
    },
    rating: 4.3,
    reviews: [
      {
        name: "Hassan",
        comment: "Good germination rate and healthy plants.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/44.jpg",
        reviewDate: "2025-06-16",
        likesCount: 6,
      },
      {
        name: "Mona",
        comment: "Tomatoes were meaty and flavorful. Will plant again.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/38.jpg",
        reviewDate: "2025-06-21",
        likesCount: 8,
      },
    ],
    stock: 41,
    price: "14 EGP/pack",
    discountPrice: "12 EGP/pack",
    category: "Seeds",
    tags: ["Seeds", "Vegetable", "Tomato", "Essential"],
  },
  {
    id: "seed-06",
    productName: "Tomato Sow Right Seeds",
    productImage: `${import.meta.env.BASE_URL}products/agriProducts/SeedsAndSaplings/tomatoSowRightSeeds.jpg`,
    images: [
      `${import.meta.env.BASE_URL}products/agriProducts/SeedsAndSaplings/tomatoSowRightSeeds.jpg`,
    ],
    description:
      "Healthy, established tomato saplings ready for transplanting. These vigorous starter plants give you a head start on the growing season and ensure earlier harvests of delicious tomatoes.",
    specs: {
      type: "Tomato Sapling",
      brand: "Sow Right",
      plantHeight: "15-20 cm",
      age: "4-6 weeks",
      potSize: "10 cm",
      readyToPlant: "Yes",
      variety: "Hybrid",
    },
    rating: 4.9,
    reviews: [
      {
        name: "Rania",
        comment:
          "Saplings arrived healthy and strong. Started producing quickly!",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/31.jpg",
        reviewDate: "2025-06-12",
        likesCount: 14,
      },
      {
        name: "Omar",
        comment: "Perfect for beginners! All plants survived transplanting.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/27.jpg",
        reviewDate: "2025-06-17",
        likesCount: 11,
      },
      {
        name: "Dalia",
        comment: "Worth the price for the time saved. Great quality plants!",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/46.jpg",
        reviewDate: "2025-06-24",
        likesCount: 9,
      },
    ],
    stock: 22,
    price: "130 EGP/plant",
    discountPrice: "115 EGP/plant",
    category: "Saplings",
    tags: ["Sapling", "Vegetable", "Tomato", "Starter Plant"],
  },
];
