export const storageProcessing = [
  {
    id: "storage-01",
    productName: "Grain Storage Bin (500kg)",
    productImage: "https://cdn.agritech.com/images/grain-storage-bin-500kg.jpg",
    images: [
      "https://cdn.agritech.com/images/grain-storage-bin-500kg.jpg",
      "https://cdn.agritech.com/images/grain-bin-interior.jpg",
      "https://cdn.agritech.com/images/storage-bin-setup.jpg",
    ],
    description:
      "Durable 500kg grain storage bin with airtight seal to protect against moisture and pests. Perfect for small to medium harvests.",
    specs: {
      capacity: "500 kg",
      material: "Food-grade Plastic",
      features: "Airtight Seal",
    },
    rating: 4.7,
    reviews: [
      {
        name: "Ahmed",
        comment: "Keeps my grains perfectly dry!",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/33.jpg",
        reviewDate: "2025-06-08",
        likesCount: 22,
      },
      {
        name: "Fatma",
        comment: "Very sturdy and well-designed.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/36.jpg",
        reviewDate: "2025-06-10",
        likesCount: 18,
      },
    ],
    stock: 25,
    price: "2200 EGP",
    discountPrice: "2100 EGP",
    category: "Storage Solutions",
    tags: ["Grain", "Storage", "Airtight"],
  },
  {
    id: "storage-02",
    productName: "Cold Storage Box (Portable)",
    productImage:
      "https://cdn.agritech.com/images/cold-storage-box-portable.jpg",
    images: [
      "https://cdn.agritech.com/images/cold-storage-box-portable.jpg",
      "https://cdn.agritech.com/images/cold-box-insulation.jpg",
    ],
    description:
      "Portable cold storage box with excellent insulation, ideal for temporary storage of perishable crops during transport.",
    specs: {
      capacity: "150 Liters",
      insulation: "High-density",
      portability: "Wheels Included",
    },
    rating: 4.6,
    reviews: [
      {
        name: "Omar",
        comment: "Perfect for market days!",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/29.jpg",
        reviewDate: "2025-06-12",
        likesCount: 19,
      },
      {
        name: "Nora",
        comment: "Keeps vegetables fresh for hours.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/32.jpg",
        reviewDate: "2025-06-13",
        likesCount: 15,
      },
    ],
    stock: 18,
    price: "1350 EGP",
    discountPrice: "1300 EGP",
    category: "Storage Solutions",
    tags: ["Cold Storage", "Portable", "Insulated"],
  },
  {
    id: "storage-03",
    productName: "Vacuum Sealer Machine",
    productImage: "https://cdn.agritech.com/images/vacuum-sealer-machine.jpg",
    images: [
      "https://cdn.agritech.com/images/vacuum-sealer-machine.jpg",
      "https://cdn.agritech.com/images/vacuum-sealer-action.jpg",
    ],
    description:
      "Professional vacuum sealer machine that extends shelf life of produce by removing air from packaging. Essential for food preservation.",
    specs: {
      sealingWidth: "30 cm",
      operation: "Automatic",
      bags: "Compatible with all",
    },
    rating: 4.8,
    reviews: [
      {
        name: "Karim",
        comment: "Extends freshness by weeks!",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/35.jpg",
        reviewDate: "2025-06-05",
        likesCount: 27,
      },
      {
        name: "Laila",
        comment: "Easy to use and very effective.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/38.jpg",
        reviewDate: "2025-06-07",
        likesCount: 21,
      },
    ],
    stock: 32,
    price: "950 EGP",
    discountPrice: "880 EGP",
    category: "Processing Equipment",
    tags: ["Vacuum", "Sealer", "Preservation"],
  },
  {
    id: "storage-04",
    productName: "Solar Dehydrator (Multi-Tier)",
    productImage:
      "https://cdn.agritech.com/images/solar-dehydrator-multi-tier.jpg",
    images: [
      "https://cdn.agritech.com/images/solar-dehydrator-multi-tier.jpg",
      "https://cdn.agritech.com/images/dehydrator-in-sun.jpg",
    ],
    description:
      "Eco-friendly multi-tier solar dehydrator that uses solar energy to dry fruits, vegetables, and herbs naturally.",
    specs: { tiers: "5 Trays", capacity: "8 kg", power: "Solar Only" },
    rating: 4.9,
    reviews: [
      {
        name: "Youssef",
        comment: "Amazing for drying herbs and fruits!",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/41.jpg",
        reviewDate: "2025-06-03",
        likesCount: 34,
      },
      {
        name: "Salma",
        comment: "No electricity costs - brilliant!",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/44.jpg",
        reviewDate: "2025-06-04",
        likesCount: 29,
      },
    ],
    stock: 15,
    price: "1700 EGP",
    discountPrice: "1600 EGP",
    category: "Processing Equipment",
    tags: ["Solar", "Dehydrator", "Eco-friendly"],
  },
  {
    id: "storage-05",
    productName: "Plastic Crates (Set of 5)",
    productImage: "https://cdn.agritech.com/images/plastic-crates-set-5.jpg",
    images: [
      "https://cdn.agritech.com/images/plastic-crates-set-5.jpg",
      "https://cdn.agritech.com/images/crates-stacked.jpg",
    ],
    description:
      "Set of 5 durable plastic crates perfect for harvesting, transport, and storage of various crops. Stackable design saves space.",
    specs: {
      quantity: "5 Crates",
      material: "Reinforced Plastic",
      stackable: "Yes",
    },
    rating: 4.5,
    reviews: [
      {
        name: "Mahmoud",
        comment: "Very sturdy and versatile!",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/27.jpg",
        reviewDate: "2025-06-14",
        likesCount: 16,
      },
      {
        name: "Dina",
        comment: "Perfect for tomato harvesting.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/30.jpg",
        reviewDate: "2025-06-15",
        likesCount: 13,
      },
    ],
    stock: 60,
    price: "350 EGP",
    discountPrice: "320 EGP",
    category: "Storage Solutions",
    tags: ["Crates", "Plastic", "Stackable"],
  },
  {
    id: "storage-06",
    productName: "Steel Grain Silo (2 Tons)",
    productImage: "https://cdn.agritech.com/images/steel-grain-silo-2tons.jpg",
    images: [
      "https://cdn.agritech.com/images/steel-grain-silo-2tons.jpg",
      "https://cdn.agritech.com/images/silo-installation.jpg",
    ],
    description:
      "Industrial-grade 2-ton steel grain silo with moisture control and ventilation systems. Ideal for commercial farming operations.",
    specs: {
      capacity: "2 Tons",
      material: "Galvanized Steel",
      features: "Ventilation System",
    },
    rating: 4.9,
    reviews: [
      {
        name: "Ali",
        comment: "Professional quality for large harvests!",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/45.jpg",
        reviewDate: "2025-06-01",
        likesCount: 41,
      },
      {
        name: "Rania",
        comment: "Worth every penny for grain storage.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/48.jpg",
        reviewDate: "2025-06-02",
        likesCount: 36,
      },
    ],
    stock: 8,
    price: "13500 EGP",
    discountPrice: "12900 EGP",
    category: "Storage Solutions",
    tags: ["Silo", "Steel", "Commercial"],
  },
  {
    id: "storage-07",
    productName: "Manual Fruit Pulping Machine",
    productImage:
      "https://cdn.agritech.com/images/manual-fruit-pulping-machine.jpg",
    images: [
      "https://cdn.agritech.com/images/manual-fruit-pulping-machine.jpg",
      "https://cdn.agritech.com/images/pulping-demonstration.jpg",
    ],
    description:
      "Manual fruit pulping machine for extracting pulp from tomatoes, apples, and other soft fruits. Easy to operate and clean.",
    specs: {
      capacity: "20 kg/hour",
      operation: "Manual Crank",
      materials: "Stainless Steel",
    },
    rating: 4.4,
    reviews: [
      {
        name: "Hassan",
        comment: "Great for making tomato paste!",
        rating: 4,
        image: "https://randomuser.me/api/portraits/men/31.jpg",
        reviewDate: "2025-06-09",
        likesCount: 14,
      },
      {
        name: "Mona",
        comment: "Easy to use and very efficient.",
        rating: 5,
        image: "https://randomuser.me/api/portraits/women/34.jpg",
        reviewDate: "2025-06-11",
        likesCount: 18,
      },
    ],
    stock: 28,
    price: "780 EGP",
    discountPrice: "720 EGP",
    category: "Processing Equipment",
    tags: ["Pulping", "Manual", "Fruit"],
  },
  {
    id: "storage-08",
    productName: "Vegetable Washer (Rotating Drum)",
    productImage:
      "https://cdn.agritech.com/images/vegetable-washer-rotating-drum.jpg",
    images: [
      "https://cdn.agritech.com/images/vegetable-washer-rotating-drum.jpg",
      "https://cdn.agritech.com/images/washer-in-action.jpg",
    ],
    description:
      "Rotating drum vegetable washer that gently cleans produce without damage. Perfect for root vegetables and leafy greens.",
    specs: {
      capacity: "50 kg/batch",
      power: "Electric Motor",
      drumMaterial: "Food-grade Stainless",
    },
    rating: 4.7,
    reviews: [
      {
        name: "Samir",
        comment: "Saves hours of manual washing!",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/37.jpg",
        reviewDate: "2025-06-06",
        likesCount: 23,
      },
      {
        name: "Yasmin",
        comment: "Gentle on delicate vegetables.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/40.jpg",
        reviewDate: "2025-06-07",
        likesCount: 19,
      },
    ],
    stock: 14,
    price: "2400 EGP",
    discountPrice: "2300 EGP",
    category: "Processing Equipment",
    tags: ["Washer", "Rotating", "Cleaning"],
  },
  {
    id: "storage-09",
    productName: "Food-Grade Jute Bags (100kg)",
    productImage:
      "https://cdn.agritech.com/images/food-grade-jute-bags-100kg.jpg",
    images: [
      "https://cdn.agritech.com/images/food-grade-jute-bags-100kg.jpg",
      "https://cdn.agritech.com/images/jute-bags-stacked.jpg",
    ],
    description:
      "Natural food-grade jute bags perfect for storing grains, pulses, and other dry crops. Breathable and eco-friendly.",
    specs: {
      capacity: "100 kg",
      material: "Natural Jute",
      features: "Breathable Fabric",
    },
    rating: 4.6,
    reviews: [
      {
        name: "Khaled",
        comment: "Perfect for grain storage!",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/39.jpg",
        reviewDate: "2025-06-13",
        likesCount: 17,
      },
      {
        name: "Nada",
        comment: "Eco-friendly and durable.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/42.jpg",
        reviewDate: "2025-06-14",
        likesCount: 14,
      },
    ],
    stock: 100,
    price: "120 EGP",
    discountPrice: "100 EGP",
    category: "Storage Solutions",
    tags: ["Jute", "Bags", "Eco-friendly"],
  },
  {
    id: "storage-10",
    productName: "Digital Weighing Scale (100kg)",
    productImage:
      "https://cdn.agritech.com/images/digital-weighing-scale-100kg.jpg",
    images: [
      "https://cdn.agritech.com/images/digital-weighing-scale-100kg.jpg",
      "https://cdn.agritech.com/images/scale-measurement.jpg",
    ],
    description:
      "High-precision digital weighing scale with 100kg capacity and clear LCD display. Essential for accurate crop measurement.",
    specs: {
      capacity: "100 kg",
      accuracy: "±50 grams",
      display: "LCD Digital",
    },
    rating: 4.8,
    reviews: [
      {
        name: "Mostafa",
        comment: "Very accurate and easy to read!",
        rating: 5,
        image: "https://randomuser.me/api/portraits/men/43.jpg",
        reviewDate: "2025-06-04",
        likesCount: 25,
      },
      {
        name: "Hana",
        comment: "Perfect for market sales.",
        rating: 4,
        image: "https://randomuser.me/api/portraits/women/46.jpg",
        reviewDate: "2025-06-05",
        likesCount: 20,
      },
    ],
    stock: 35,
    price: "950 EGP",
    discountPrice: "900 EGP",
    category: "Processing Equipment",
    tags: ["Scale", "Digital", "Weighing"],
  },
];
